<?php
// Genera vendor/autoload_runtime.php si el plugin de symfony/runtime no lo hizo.
// El contenido es equivalente al que generaría ComposerPlugin::updateAutoloadFile()
// para Lycet: sin extra.runtime, runtime class = SymfonyRuntime, project_dir = dirname(__DIR__, 1).
$target = getcwd() . '/vendor/autoload_runtime.php';

if (file_exists($target)) {
    echo "vendor/autoload_runtime.php ya existe.\n";
    exit(0);
}

$content = <<<'PHP'
<?php

// autoload_runtime.php @generated by Symfony Runtime

if (true === (require_once __DIR__.'/autoload.php') || empty($_SERVER['SCRIPT_FILENAME'])) {
    return;
}

if (PHP_VERSION_ID < 80000 && in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    ob_start();
    $app = require $_SERVER['SCRIPT_FILENAME'];
    ob_end_clean();
} else {
    $app = require $_SERVER['SCRIPT_FILENAME'];
}

if (!is_object($app)) {
    throw new TypeError(sprintf('Invalid return value: callable object expected, "%s" returned from "%s".', get_debug_type($app), $_SERVER['SCRIPT_FILENAME']));
}

$runtime = $_SERVER['APP_RUNTIME'] ?? $_ENV['APP_RUNTIME'] ?? 'Symfony\\Component\\Runtime\\SymfonyRuntime';
$runtime = new $runtime(($_SERVER['APP_RUNTIME_OPTIONS'] ?? $_ENV['APP_RUNTIME_OPTIONS'] ?? []) + [
  'project_dir' => dirname(__DIR__, 1),
]);

[$app, $args] = $runtime
    ->getResolver($app)
    ->resolve();

$app = $app(...$args);

exit(
    $runtime
        ->getRunner($app)
        ->run()
);
PHP;

file_put_contents($target, $content . "\n");
echo "vendor/autoload_runtime.php generado con template de SymfonyRuntime 5.4.\n";
