-- Migration 042: (SUPERADA por 045)
--
-- Esta migración introdujo un diseño per-ferretería para los estados de pedido
-- (tabla pedido_estados con ferreteria_id + columna pedidos.estado_id UUID).
-- Resultó ser el enfoque equivocado: los slugs de estado son universales en todo
-- el sistema (máquina de estados XState, bot, webhooks), no per-tenant, y migrar a
-- estado_id habría obligado a reescribir 30+ archivos.
--
-- El diseño correcto (catálogo GLOBAL por slug + FK) vive en:
--   045_pedido_estados_catalogo.sql
--
-- La 045 limpia idempotentemente lo que esta migración dejó (DROP COLUMN estado_id,
-- DROP TABLE pedido_estados per-ferretería) antes de crear el catálogo global.
-- Se deja este archivo como no-op documentado para preservar el historial.

-- (sin operaciones)
